# -*- coding: utf-8 -*-
"""Array2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_IMF-c4CPPU3oLEZAjX0oCPx32W3BFnO
"""

print("Bem vindos á Noboticário!!!")

lista_produtos = ['máscaras faciais', 'batons', 'esmaltes', 'perfumes', 'loções', 'shampoos', 'sabonetes', 'delineadores']

for i in range(len(lista_produtos)):
  print("Nós temos", lista_produtos[i], "à venda")