# -*- coding: utf-8 -*-
"""Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fArfgqHJtRrvaxbrhHgH7L6PlAClfQ3L
"""

lista_musicos = [ 'Djavan', 'Roberto Carlos', 'Elis Regina', 'Tom Jobim', 'Milton Nascimento', 'Chico Buarque', 'Nara Leão', 'Pitty', 'Simonal', 'Moacir Santos', 'Caetano Veloso', 'Elza Soares', 'Paulinho da Viola', 'Yamandú Costa', 'Gal Costa']
quantidade_musicos = len(lista_musicos)

print(quantidade_musicos)
print(lista_musicos[2])
print(lista_musicos[9])
print(lista_musicos[14])