# -*- coding: utf-8 -*-
"""Atv_HTML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xg7RgnYTbl6iIkG4QhofVWKJwaqUFVfC
"""

loja_eletro = ["notebook", "tablet", "celular", "computador", "headphone"]
print(loja_eletro)

ano = [2004, 2011, 2006, 1982, 2005]
print(ano)