# -*- coding: utf-8 -*-
"""Cdg_calc_reset.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jOw3Ic9rbLVyL70L0q1DpmRWLGpLQxHm
"""

def calc(num1, num2, operador):
    if (operador == 1):
      resp = num1 + num2
    elif (operador == 2):
      resp = num1 - num2
    elif (operador == 3):
      resp = num1 * num2
    elif (operador == 4):
          resp = num1 / num2
    return int(resp)

sair = False



while (sair == False):
  print("Para calcular leve em consideração as operações são: 0 = Reset, 1 = Soma, 2 = Subtração, 3 = Multiplicação e 4 = Divisão")
  print("Além de que deve se seguir uma sequência: operação, numero1 e numero2")

  operador = int(input("Número do operador?"))
  if (operador == 0):
    print("Resetando")
    sair == True
  elif(operador < 0 or operador > 4):
    print("Comando de operação inválido")
  else:
    num1 = int(input("Numero1?"))
    num2 = int(input("Numero2?"))

    resp = calc(num1, num2, operador)
    print(resp)