# -*- coding: utf-8 -*-
"""Cdg.Atv

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15N4yQ284OBuZccv59NAmiGKsAMk6sQl-
"""

num = 20
cont = True

while(num>0):
  print(num,"° Andar")
  num = num  - 1
  if (num == 13):
     num = num - 1

"""O mesmo código sem o uso do "While"
"""

num = 20
cont = 20

for i in range(num, 0, -1):
  if (i == 13):
   continue
  print(i,"° Andar")